language: node_js
node_js:
  - "0.10"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g karma-cli

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots,coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage