language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g karma-cli

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=[dots,coverage] --browsers=PhantomJS && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage